version: '3.4'

services:
  conta-corrente-api:
    build:
      context: .
      dockerfile: ContaCorrente.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
